# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  displayName: 'Running tests'
  inputs:
    actions: 'test'
    sdk: 'iphonesimulator'
    configuration: 'Debug'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    scheme: '$(scheme)'
    xcodeVersion: 'default'
    useXcpretty: true
    publishJUnitResults: true
    args: '-destination "platform=iOS Simulator,name=iPad Air (4th generation)"'


- task: PublishTestResults@2
  displayName: 'Publishing test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/junit.xml'
    mergeTestResults: true
    failTaskOnFailedTests: true